# Generated by Django 4.1.6 on 2023-03-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberRoom', models.CharField(max_length=255, unique=True)),
                ('Link', models.CharField(max_length=255)),
                ('statusCamera', models.BooleanField(default=False)),
            ],
        ),
    ]
