version: '3.7'

services:

  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "sqldata:/var/lib/mysql"
  
  web:
    image: checkchuekun:latest
    ports:
      - "8000:8000"
    command: bash -c "pipenv run python manage.py makemigrations  && pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=CheckchuekunApp.settings
    working_dir: /app
  
  celery:
    image: checkchuekun:latest
    command: bash -c "pipenv run celery -A CheckchuekunApp worker -l info --pool=prefork --concurrency=8"
    environment:
      C_FORCE_ROOT: "true"
    depends_on:
      - db
    volumes:
      - .:/app

  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - "redisdata:/data"

volumes:
  sqldata:
  redisdata: